version: "2"
services:
  web:
    build: .
    ports:
      - "3001:3001"
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
#    volumes:
#      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"